export const types = Object.freeze({
  WEATHER_START_FETCHING: 'TODO_START_FETCHING',
  WEATHER_STOP_FETCHING: 'WEATHER_STOP_FETCHING',
  WEATHER_ERROR_FETCHING:'WEATHER_ERROR_FETCHING',
  WEATHER_FILL: 'WEATHER_FILL',
});